name: Compile Database
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 12 * * *"

permissions:
  contents: write

jobs:
  pacman:
    runs-on: ubuntu-22.04
    container: archlinux
    steps:
      - uses: actions/checkout@v3
      - run: pacman -Syu --noconfirm git python python-requests
      - run: bash build.sh
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Updated Package List"
          git push
